### ISSUE TITLE
To allow the user to have a custom background 

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#146]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Only 2 restricted themes available ,the ability to the user to atleast be able to add a custom background

**Would you like to work on the issue?**
Yes
```

**Comment by stealthanthrax** [comment]
@zamhaq,can I start working on it?

**Comment by gabru-md** [comment]
@stealthanthrax why is it even needed?

**Comment by gabru-md** [comment]
It is supposed to be a light weight chrome extension to be easy to use and faster to load. 
A user can definitely go to chat.susi.ai to get all the features he/she wants. I guess adding so many features will make it heavy and increase the loading time and size therefore defying the purpose of it to be light weight and ready to use extension.
@zamhaq please comment something.

**Comment by zamhaq** [comment]
@gabru-md Yeah, my initial thought about the extension was same, but now many features are being implemented, eg the `login` feature is also being implemented since it was already implemented in `firefox bot`, so it was decided to add the features and let the user decide what he wants or not.
@stealthanthrax yes you can go ahead, but when implementing this feature keep in mind that if background becomes too light or dark the text might not be visible, so that should be changed accordingly.

**Comment by gabru-md** [comment]
@zamhaq thanks!

These were just my thoughts that i wanted to share. Rest i respect what you say. So i guess this can be worked upon.

**Comment by stealthanthrax** [comment]
@gabru-md @zamhaq , any suggestions regarding the placement of url input bar?

**Comment by stealthanthrax** [comment]
I was thinking of adding a **simple input bar** under the susi heading
