### ISSUE TITLE
Clean up the repo and add a GIF

### ISSUE THREAD

**Issue by gabru-md** [fossasia/susi_chromebot#45]
move all the Extension related data inside a `src` folder.
Leaving only `README` and `LICENSE` outside it.

And add a GIF to the `README` demonstrating the working of extension.

@ms10398 @zamhaq I will work on this only if you guys agree to it as an enhancement.
Thanks!

**Comment by zamhaq** [comment]
@gabru-md Sure do that. Also update `README` regarding how to load the extension, because I think that pushing extension related things into `src` might change the way to load them. Also, if it is possible create a `contributing.md` and put links to `FOSSASIA best practices`, move the **Installation** and put it in `contributing.md` and also put some of your own guidelines which you might think are necessary.

I will work on reducing redundancy in the code #46. Thanks.

**Comment by gabru-md** [comment]
Surely will!
