### ISSUE TITLE
Wrong response read from server

### ISSUE THREAD

**Issue by hkedia321** [fossasia/susi_chromebot#80]
**actual behaviour**
Currently, the `answers[0].data[0]` field is being read. This is not the correct response to read. Wrongly, the request is being send twice from the client side.
![image](https://user-images.githubusercontent.com/17807257/30932104-1b640a14-a3e4-11e7-9fa3-dbb74b6f6bd3.png)

**Expected behaviour**
Send the request only once for one query. Read the correct response which is the `actions` attribute.
**Please refer to the API doc at** https://dev.susi.ai/skills/susi_chat_api.html

**Would you like to work on this ?**
No

**Comment by zamhaq** [comment]
@gabru-md what about this ? I would like to work on it.

**Comment by gabru-md** [comment]
Yes sure you may.

**Comment by zamhaq** [comment]
@gabru-md it seems that chat.susi.ai return the same responses. Please test and confirm. If that's so, then this can wait.

**Comment by zamhaq** [comment]
@gabru-md would you take a look into this? According to the issue, the response read is wrong, but if we go with reading the `actions` attribute then we won't get the required data. for e.g:- 
![actions](https://user-images.githubusercontent.com/20766601/31044731-6d5d6076-a5f2-11e7-956e-6e13dfabfd2d.png)
In case we go with searching `Manish Devgan` the `actions` attribute will not provide the necessary images. So, what do you think?
And about request sent twice, I have seen that it returns the same last query instead of the new one. But, that does give a load on the server? I think we should remove it since that happens only rarely.

**Comment by gabru-md** [comment]
@zamhaq I'll look into it. And will try to make a PR in a day or two.
You can assign this issue to me thanks!

**Comment by zamhaq** [comment]
great

**Comment by zamhaq** [comment]
@gabru-md whats the status? Did you take a look?

**Comment by gabru-md** [comment]
@zamhaq i was ill. thats why i mentioned that i will start working on it in a day or two.

I will start working on it today

**Comment by ms10398** [comment]
@gabru-md If you need any help just drop me a message always willing to help 
:+1:

**Comment by zamhaq** [comment]
@gabru-md @ms10398 we need to support different type of responses like the rss and table response. If you are on it then do one more thing, change the width of the message to occupy the full width of box to make messages and content look cleaner and understandable.

**Comment by ms10398** [comment]
@gabru-md Whats the status on this.

**Comment by zamhaq** [comment]
@ms10398 I'll be working on this from now. 
You can work on other issues assigned to @gabru-md as he won't be able to. Thanks.

**Comment by ms10398** [comment]
@zamhaq go ahead as you make the chat read the right data from server.
I will try to implement feature to support of all types of responses

**Comment by zamhaq** [comment]
@ms10398 I'll try to do that in this issue itself if possible. Meanwhile, you can work on other issues that are open. :+1:
